### ISSUE TITLE
how to modify GEM5 to generate trace as input of simnet

### ISSUE THREAD

**Issue by asds25810** [lingda-li/simnet#1]
Hi Lingda,

simnet is a really impressive work! 

I'm trying to use it for more programs. Could you please give me some suggestions about how to modify GEM5 to generate trace as input of simnet? Using debug flags of GEM5, such as ROB, cache, Exec, generates too much data. How can I generate trace for a program with the same format as the provided 500.perlbench_r.10m.txt?

Thanks!

**Comment by lingda-li** [comment]
Hi,

Thanks for your interest!

The modified gem5 code that can generate SimNet input is at https://github.com/lingda-li/gem5, and the `ml-sim` branch. You should checkout the commit 17cfbb10f47e89aadf73c97df43c96e9cd441891, which I think is the right version for SimNet (but cannot guarantee). The output trace should be in the folder where simulation gets executed.

**Comment by asds25810** [comment]
Hi Lingda,

I have successfully reproduced the pipeline of simnet. As the papers (sigmetrics 2022 and SC 2022) introduced, if run simnet without subtrace parallel, it shows really low MIPS (e.g., 0.005 MIPS on a 3080ti), due to the heavy computation of the neural network.  

I don't quite understand the role of the neural network, as subtrace parallel seems like the key to accelerate simulation.  What if use another faster trace-driven simluator plus subtrace parallel?

**Comment by lingda-li** [comment]
Glad that you were able to reproduce. Feel free to submit pull requests to maybe help other people. About your question, neural network is much more regular and parallel. On the other hand you can potential use a CPU thread to simulate each subtrace on CPU using traditional simulators, but there is irregularity between threads, and it won't generate as nearly much parallelism as the GPU case to accelerate neural network.
